### ISSUE TITLE
Takes forever to npm install

### ISSUE THREAD

**Issue by gabalicious** [stewartlord/contrast#1]
Are all these dependencies needed? Seems like NPM installs a lot of stuff that might not be needed
Example
`[2/3] ⠄ nodegit: CC(target) Release/obj.target/openssl/vendor/openssl/openssl/crypto/des/des_enc.o`

**Comment by stewartlord** [comment]
Hi Justin, sorry it’s taking so long. I’m pretty sure all of the dependencies are used, but if you find one we can remove that would be great!
